/*
Copyright 2018 Neeraj Shah

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package io.artofcode;

import com.google.gson.*;

/**
 * This class wraps Google Gson parser and helps in converting JSON to POJO
 *
 * @author Neeraj Shah
 * @since 0.1
 * */
class EntityMapper<T> {

    private final Gson gson;

    /**
     * Class type of POJO which needs to be generated from the JSON payload
     * */
    private final Class<T> typeOf;

    public EntityMapper(Class<T> typeOf) {
        gson = new Gson();
        this.typeOf = typeOf;
    }

    /**
     *
     * @param json - The JSON payload generated by serailizing the POJO
     *
     * @return POJO of type T created by parsing passed json payload
     * */
    public T parse(String json) {
        return gson.fromJson(json, typeOf);
    }
}